# Generated by Django 5.1.2 on 2024-12-26 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='branch',
        ),
        migrations.AddField(
            model_name='customer',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='shop.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='shop.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='shop.business'),
            preserve_default=False,
        ),
    ]
