# Generated by Django 4.2.4 on 2023-09-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_branch_email_alter_car_license_alter_car_vin_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch", options={"verbose_name_plural": "Branches"},
        ),
        migrations.AlterModelOptions(
            name="business", options={"verbose_name_plural": "Businesses"},
        ),
    ]
