# Generated by Django 4.2.4 on 2024-02-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_service_delete_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='estimated_time',
            field=models.CharField(blank=True, choices=[('1 hr', '1 hr'), ('2 hrs', '2 hrs'), ('3 hrs', '3 hrs'), ('4 hrs', '4 hrs'), ('5 hrs', '5 hrs'), ('6 hrs', '6 hrs'), ('7 hrs', '7 hrs'), ('8 hrs', '8 hrs'), ('1+ day', '1+ day')], default='', max_length=30),
        ),
    ]
