# Generated by Django 4.2.4 on 2024-01-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_vehicle_license_alter_vehicle_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='license',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
