# Generated by Django 4.2.4 on 2024-01-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_vehicle_license_alter_vehicle_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vehicles',
            field=models.ManyToManyField(blank=True, to='shop.vehicle'),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
