# Generated by Django 4.2.4 on 2023-09-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_branch_options_alter_business_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="branch", old_name="business_id", new_name="business",
        ),
    ]
