# Generated by Django 4.2.4 on 2024-02-27 04:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_service_estimated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Oil, lube, and filter', 'Oil, lube, and filter'), ('Diagnostic', 'Diagnostic'), ('Tire rotation', 'Tire rotation'), ('Brake replacement', 'Brake replacement'), ('Alignment', 'Alignment'), ('Transmission', 'Transmission'), ('Electrical systems', 'Electrical systems'), ('Other', 'Other')], max_length=112),
        ),
    ]
