# Generated by Django 5.1.2 on 2025-03-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_business_default_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
