# Generated by Django 5.1.2 on 2024-10-26 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_customuser_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='shop.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimate',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='shop.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='shop.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='shop.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='shop.business'),
            preserve_default=False,
        ),
    ]
