# Generated by Django 4.2.4 on 2024-02-28 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_service_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='shop.vehicle'),
        ),
    ]
