# Generated by Django 4.2.4 on 2023-09-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_rename_business_id_branch_business"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice", old_name="customer_id", new_name="customer",
        ),
        migrations.RenameField(model_name="owner", old_name="car_id", new_name="car",),
        migrations.RenameField(
            model_name="owner", old_name="customer_id", new_name="customer",
        ),
    ]
