# Generated by Django 5.1.2 on 2025-03-07 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_business_address_alter_business_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.branch'),
        ),
    ]
