# Generated by Django 5.1.2 on 2025-04-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_customuser_current_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='default_pricing',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
