# Generated by Django 4.2.4 on 2023-09-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_rename_customer_id_invoice_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="license",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="vin",
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
