# Generated by Django 4.2.4 on 2024-04-01 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_service_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='date',
            new_name='datetime',
        ),
    ]
