# Generated by Django 4.2.4 on 2023-09-05 03:07

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_car_license_alter_car_vin"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="shop.branch",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="shop.branch",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="branch",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="shop.business",
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="car",
            name="license",
            field=models.CharField(blank=True, default="", max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="vin",
            field=models.CharField(blank=True, default="", max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="customer",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, default="", max_length=128, region=None, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="shop.customer",
            ),
        ),
    ]
