# Generated by Django 5.1.2 on 2025-04-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_branch_default_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='default_pricing',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='default_pricing',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
