# Generated by Django 4.2.4 on 2024-04-02 03:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_date_service_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Oil lube and filter', 'Oil lube and filter'), ('Diagnostic', 'Diagnostic'), ('Tire rotation', 'Tire rotation'), ('Brake replacement', 'Brake replacement'), ('Alignment', 'Alignment'), ('Transmission', 'Transmission'), ('Electrical systems', 'Electrical systems'), ('Other', 'Other')], max_length=110),
        ),
    ]
