# Generated by Django 4.2.4 on 2023-09-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_car_branch_customer_branch_alter_branch_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='branch',
        ),
    ]
