# Generated by Django 4.2.4 on 2023-09-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_car_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
