# Generated by Django 4.2.4 on 2024-05-05 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_estimate_estimateitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimateitem',
            old_name='amount',
            new_name='price',
        ),
    ]
