# Generated by Django 4.2.4 on 2024-05-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_amount_estimateitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimateitem',
            old_name='price',
            new_name='labor_price',
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='part_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
