# Generated by Django 4.2.4 on 2024-07-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_serviceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='labor_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='part_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
