# Generated by Django 4.2.4 on 2024-07-25 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_serviceitem_labor_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='estimate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='shop.estimate'),
        ),
    ]
