# Generated by Django 4.2.4 on 2024-08-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_service_estimate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='services',
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='labor_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='part_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
