# Generated by Django 4.2.4 on 2024-10-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_vendor_alter_service_estimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
