# Generated by Django 4.2.4 on 2024-10-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_vendor_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='completed',
            field=models.CharField(blank=True, choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Contact Customer - Approval', 'Contact Customer - Approval'), ('Contact Customer - Pickup', 'Contact Customer - Pickup'), ('Waiting on Pickup', 'Waiting on Pickup'), ('Waiting on Parts', 'Waiting on Parts'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Scheduled', max_length=30),
        ),
    ]
