# Generated by Django 4.2.4 on 2024-10-14 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_service_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='completed',
            new_name='status',
        ),
    ]
